config/routes.rb
Rails.application.routes.draw do
	root to: "lists#index"
	resources :lists do
		resources :list_items
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/soft_deletable.rb
module SoftDeletable
  extend ActiveSupport::Concern
  included do
    default_scope { where(is_deleted: false) }
    scope :only_deleted, -> { unscope(where: :is_deleted).where(is_deleted: true) }
  end

  def delete
    update_column :is_deleted, true if has_attribute? :is_deleted
  end

  def destroy;
    callbacks_result = transaction do
      run_callbacks(:destroy) do
        delete
      end
    end
    callbacks_result ? self : false
  end

end

app/models/list.rb
class List < ApplicationRecord
	self.per_page = 10
	include SoftDeletable
	validates :name, presence: true
	has_many :list_items, inverse_of: :list, dependent: :destroy

	accepts_nested_attributes_for :list_items, reject_if: :all_blank, allow_destroy: true
end

app/models/list_item.rb
class ListItem < ApplicationRecord
	self.per_page = 10
	include SoftDeletable
	validates :name, presence: true
  belongs_to :list
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

	def not_found
	  render :file => "#{Rails.root}/public/404.html",  :status => 404
	end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:edit, :destroy, :update]

  def index
  	@lists = List.paginate(page: params[:page])
  end

  def new
  	@list = List.new
  end

  def create
  	@list = List.new(list_params)
  	if @list.save
  		redirect_to root_path, notice: 'List was successfully created'
  	else
  		render :new
  	end
  end

  def update
  	if @list.update(list_params)
  		redirect_to root_path, notice: 'List was successfully updated'
  	else
  		render :new
  	end
  end

  def destroy
  	@list.destroy
  	redirect_to root_path, notice: 'List was successfully deleted'
  end

  private
  	def list_params
  		params.require(:list).permit(:name, list_items_attributes:[:name, :id, :_destroy])
  	end

  	def find_list
  		@list = List.find_by(id: params[:id])
  		return not_found if @list.nil?
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UmaiAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/flash'%>
    <%= yield %>
  </body>
</html>

app/views/list_items/edit.html.erb
<h1>ListItems#edit</h1>
<p>Find me in app/views/list_items/edit.html.erb</p>

app/views/list_items/index.html.erb
<h1>ListItems#index</h1>
<p>Find me in app/views/list_items/index.html.erb</p>

app/views/list_items/new.html.erb
<h1>ListItems#new</h1>
<p>Find me in app/views/list_items/new.html.erb</p>

app/views/list_items/show.html.erb
<h1>ListItems#show</h1>
<p>Find me in app/views/list_items/show.html.erb</p>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f|%>
	<p><%= f.input :name%></p>
	<h3>List Items</h3>
	<div id="list_items">
		<%= f.simple_fields_for :list_items, (@list.list_items.blank? ? @list.list_items.build : @list.list_items) do |list_item|%>
			<%= render 'list_item_fields', f: list_item%>
			<div class="links">
				<%= link_to_add_association 'add list item', f, :list_items%>
			</div>
		<% end %>
	</div>
	<p><%= f.submit%></p>
<% end %>

app/views/lists/_list_item_fields.html.erb
<p>
	<div class="nested-fields">
	  <%= f.input :name%>
	  <%= link_to_remove_association "remove item", f%>
	</div>
</p>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
<%=render 'form'%>

app/views/lists/index.html.erb
<h1>Lists</h1>
<table border="1">
	<thead>
		<tr>
			<td>Id</td>
			<td>Name</td>
			<td>List Items</td>
			<td>Actions</td>
		</tr>
	</thead>
	<tbody>
		<% @lists.each do |list| %>
			<tr>
				<td><%= list.id %></td>
				<td><%= list.name%></td>
				<td><%= link_to list.list_items.limit(5).pluck(:name).to_sentence, list_list_items_path(list)%></td>
				<td>
					<%= link_to 'Edit', edit_list_path(list)%> || 
					<%= link_to 'Delete', list_path(list), method: :delete, data: {:confirm => 'Are you sure?'}%>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<p><%= will_paginate @lists %></p>
<p><%=link_to 'Add New', new_list_path%></p>

app/views/lists/new.html.erb
<h1>Add New List</h1>
<%=render 'form'%>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>